---
# x200 specific packages and configs

- name: Install x200 packages
  pacman:
    name:
      - rofi
      - flameshot
      - alacritty
      - betterlockscreen
    state: present
    update_cache: yes

# DWM build step â€” assumes your repo has a buildable dwm directory
- name: Install build dependencies for dwm
  pacman:
    name:
      - base-devel
      - libx11
      - libxft
      - libxinerama
    state: present

- name: Build and install dwm from your config
  command: make install
  args:
    chdir: "{{ ansible_env.HOME }}/.files/dwm"
  become: yes
  when: ansible_env.HOME is defined

